eureka:
  instance:
    metadataMap:
      user: Abhishek
      password: Abhishek
      configPath: /config
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
